#!/bin/bash
instfiles="fuseisomenu.desktop fuseisomenu.sh"
KDE5SRVDIR="${HOME}/.local/share/kservices5/ServiceMenus/"
MENUDIR="${KDE5SRVDIR}/ServiceMenus"

if [ -d $KDE5MENUDIR ]; then
    mkdir -p ${MENUDIR} 2>/dev/null
    echo -n "Installing menu to $MENUDIR ... "
    cp -a $instfiles ${MENUDIR}
    [ $? -eq 0 ] && echo "OK" || echo "FAILED"
fi
echo
